### ISSUE TITLE
No worky?

### ISSUE THREAD

**Issue by claytondukes** [GreggBzz/snmp-interface-poll#1]
Trying to get this to work, I get no errors, but the /var/log/diamond/archive.log doesn't show it doing anything either.
This is on a Debian server and I followed the guide, but perhaps I am missing something. Any ideas?

/etc/diamond/collectors:

```
-rw-r--r-- 1 root root  226 Feb 29 17:28 SNMPInterfaceDiscovery.conf
-rw-r--r-- 1 root root   97 Feb 29 17:42 SNMPInterfacePoll.conf
drwxr-xr-x 2 root root 4.0K Feb 29 17:20 SNMPInterfacePoll.d
```

Note that there are no files in the SNMPInterfacePoll.d directory.

**Comment by phrend** [comment]
Same here - running on raspbian. I turned up the diamond log level to DEBUG, and I don't see anything snmp related in the diamond.log nor the archive.log - it's as if it's not running these collectors at all...?

**Comment by gummeah** [comment]
same on Centos 7, diamond 4.0.455

**Comment by gummeah** [comment]
Looks like diamond loading classes with 'Collector' in their name. I changed 'SNMPInterfaceDiscovery' to 'SNMPInterfaceDiscoveryCollector' and 'SNMPInterfacePoll' to 'SNMPInterfacePollCollector' class names and all references in collector files. Now they are loading.
But now im having other errors:

> May 30 08:05:56 python: 1464609956.76#011[SNMPInterfaceDiscoveryCollector:5275:ERROR]#011Collector failed!
> May 30 08:05:56 python: 1464609956.76#011[SNMPInterfaceDiscoveryCollector:5275:ERROR]#011/usr/lib/python2.7/site-packages/diamond/utils/scheduler.py:99
> May 30 08:05:56 python: Traceback (most recent call last):
> May 30 08:05:56 python: File "/usr/lib/python2.7/site-packages/diamond/utils/scheduler.py", line 73, in collector_process
> May 30 08:05:56 python: collector._run()
> May 30 08:05:56 python: File "/usr/lib/python2.7/site-packages/diamond/collector.py", line 472, in _run
> May 30 08:05:56 python: self.collect()
> May 30 08:05:56 python: File "/usr/share/diamond/collectors/snmp/snmp.py", line 72, in collect
> May 30 08:05:56 python: self.collect_snmp(device, host, port, community)
> May 30 08:05:56 python: File "/usr/share/diamond/collectors/snmpinterfacediscovery/snmpinterfacediscovery.py", line 292, in collect_snmp
> May 30 08:05:56 python: self.get_interface_indexes(device, host, port, community)
> May 30 08:05:56 python: File "/usr/share/diamond/collectors/snmpinterfacediscovery/snmpinterfacediscovery.py", line 175, in get_interface_indexes
> May 30 08:05:56 python: if (ifTypeData[ifTypeOid] not in self.IF_TYPES or
> May 30 08:05:56 python: KeyError: '1.3.6.1.2.1.2.2.1.3.4227441'

Error from log points here:

```
        ifIndexOid = '.'.join([self.IF_MIB_INDEX_OID])
        ifIndexData = self.walk(ifIndexOid, host, port, community)
        ifIndexes = [v for v in ifIndexData.values()]
        for ifIndex in ifIndexes:
            # Get Interface Type
            ifTypeOid = '.'.join([self.IF_MIB_TYPE_OID, ifIndex])
            ifTypeData = self.get(ifTypeOid, host, port, community)
            ifStatusOid = '.'.join([self.IF_MIB_STATUS_OID, ifIndex])
            ifStatusData = self.get(ifStatusOid, host, port, community)
            if (ifTypeData[ifTypeOid] not in self.IF_TYPES or
                    ifStatusData[ifStatusOid] not in self.IF_STATUS):
            # Skip Interface, not a status or type we care about.
                continue
```

I printed variables to file and what I get:

> ifTypeOid = 1.3.6.1.2.1.2.2.1.3.4227441
> ifTypeData = {'SNMPv2-SMI::mib-2.2.2.1.3.4227441': '117'}
> ifStatusOid = 1.3.6.1.2.1.2.2.1.8.4227441
> ifStatusData = {'SNMPv2-SMI::mib-2.2.2.1.8.4227441': '1'}

I think the problem is that some of oids are resolved and others are not.

Btw, I have this version of snmp.py collector:
[link](https://raw.githubusercontent.com/bmfurtado/Diamond/6de59ad383cc262805939d2ac30d2650c3b1ea7e/src/collectors/snmp/snmp.py)

From this [issue:](https://github.com/python-diamond/Diamond/issues/219)
`

**Comment by gummeah** [comment]
So, as I said before, I changed class names, so diamond can "see" them and load. I changed original snmp.py collector to return not resolved oids. And I changed snmpinterfacediscovery to not try generic cpu oid, but just pass, so it don't throw errors. 
And I added some IF_TYPES to gather info from in snmpinterfacediscovery.
If someone interested you can get it from here:
[link](https://github.com/gummeah/snmp-interface-poll/tree/master/src/collectors)

**Comment by mzeier** [comment]
I get this KeyError I'm not sure how to debug:

```
1489084740.04	[SNMPInterfaceDiscoveryCollector:13952:ERROR]	/usr/local/lib/python2.7/dist-packages/diamond/utils/scheduler.py:99
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/diamond/utils/scheduler.py", line 73, in collector_process
    collector._run()
  File "/usr/local/lib/python2.7/dist-packages/diamond/collector.py", line 477, in _run
    self.collect()
  File "/usr/local/share/diamond/collectors/snmp/snmp.py", line 68, in collect
    for device in self.config['devices']:
  File "/usr/local/lib/python2.7/dist-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'devices'
```

**Comment by mzeier** [comment]
The config is:

```
root@nimba:/etc/diamond/collectors# cat SNMPInterfaceDiscovery.cfg
enabled = True

interval = 14400

[devices]

[[pm-fw01]]
community =public
host = fw01
port = 161
```
